// Mock event payloads for demo — one per rule
export const MOCK_EVENTS = [
  {
    id: 'rule1',
    label: '⛽ Petrol Fill (Silent)',
    desc: 'Under daily limit — no alert',
    color: 'teal',
    event: {
      event_type: 'sms_transaction',
      timestamp: new Date().toISOString(),
      location: { name: 'HP Petrol Bunk', type: 'petrol_bunk', coordinates: { lat: 12.97, lng: 77.59 } },
      transaction: { amount: 350, merchant: 'HP Petrol', category: 'fuel', sms_raw: 'INR 350.00 debited for HP Petrol' },
      user_daily_spent: 900,
      user_daily_limit: 1200,
      category_spent: { fuel: 900, dining: 300 },
      category_budget: { fuel: 1500, dining: 2000 },
    },
  },
  {
    id: 'rule2-dining',
    label: '🍽️ Dining Overspend',
    desc: 'Daily limit exceeded — amber alert',
    color: 'amber',
    event: {
      event_type: 'sms_transaction',
      timestamp: new Date().toISOString(),
      location: { name: 'Swiggy Delivery', type: 'restaurant', coordinates: { lat: 12.97, lng: 77.64 } },
      transaction: { amount: 450, merchant: 'Swiggy', category: 'dining', sms_raw: 'INR 450.00 debited for Swiggy' },
      user_daily_spent: 1380,
      user_daily_limit: 1200,
      category_spent: { dining: 1750, shopping: 800 },
      category_budget: { dining: 2000, shopping: 3000 },
    },
  },
  {
    id: 'rule2-hospital',
    label: '🏥 Hospital Bill',
    desc: 'Medical overspend — gentle alert',
    color: 'amber',
    event: {
      event_type: 'sms_transaction',
      timestamp: new Date().toISOString(),
      location: { name: 'Manipal Hospital', type: 'hospital', coordinates: { lat: 12.94, lng: 77.60 } },
      transaction: { amount: 2200, merchant: 'Manipal Hospital', category: 'hospital', sms_raw: 'INR 2200.00 debited for Manipal Hospital' },
      user_daily_spent: 2800,
      user_daily_limit: 1200,
      category_spent: { dining: 300, shopping: 300 },
      category_budget: { dining: 2000, shopping: 3000 },
    },
  },
  {
    id: 'rule3-mall',
    label: '🏪 Enter Mall',
    desc: 'Geofence pre-alert — remaining budget',
    color: 'blue',
    event: {
      event_type: 'geofence_enter',
      timestamp: new Date().toISOString(),
      location: { name: 'Phoenix MarketCity', type: 'mall', coordinates: { lat: 12.99, lng: 77.69 } },
      transaction: null,
      user_daily_spent: 700,
      user_daily_limit: 1200,
      category_spent: { shopping: 1200, dining: 500 },
      category_budget: { shopping: 3000, dining: 2000 },
    },
  },
  {
    id: 'rule3-restaurant',
    label: '🍜 Enter Restaurant',
    desc: 'Geofence — dining budget check',
    color: 'blue',
    event: {
      event_type: 'geofence_enter',
      timestamp: new Date().toISOString(),
      location: { name: 'Social Koramangala', type: 'restaurant', coordinates: { lat: 12.93, lng: 77.62 } },
      transaction: null,
      user_daily_spent: 600,
      user_daily_limit: 1200,
      category_spent: { dining: 1700, shopping: 800 },
      category_budget: { dining: 2000, shopping: 3000 },
    },
  },
  {
    id: 'rule4-bar',
    label: '🚨 Enter Bar at 11 PM',
    desc: 'CRITICAL — high volume override alert',
    color: 'red',
    event: {
      event_type: 'geofence_enter',
      timestamp: (() => { const d = new Date(); d.setHours(23, 15, 0, 0); return d.toISOString(); })(),
      location: { name: 'Vapebar & Lounge', type: 'bar', coordinates: { lat: 12.97, lng: 77.64 } },
      transaction: null,
      user_daily_spent: 1100,
      user_daily_limit: 1200,
      category_spent: { dining: 800, entertainment: 1000 },
      category_budget: { dining: 2000, entertainment: 1500 },
    },
  },
];
